name: flutter_app
description: Testing flutter

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - images/spoder.png
    - images/food.png
    - images/special.png
